# -*- coding: utf-8 -*-
"""07.07.02 Exercícios Listas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BA-7w6uZza1l-gkiU_nn-K0VJ6n-aoFQ

# Exercícios

## 1. Faturamento do Melhor e do Pior Mês do Ano

Qual foi o valor de vendas do melhor mês do Ano?
E valor do pior mês do ano?
"""

meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
vendas_1sem = [25000, 29000, 22200, 17750, 15870, 19900]
vendas_2sem = [19850, 20120, 17540, 15555, 49051, 9650]

total_meses = vendas_1sem + vendas_2sem

maior_venda = max(total_meses)
pior_venda = min(total_meses)
indice_melhor_mes = total_meses.index(maior_venda) 
indice_pior_mes = total_meses.index(pior_venda)

print(f'O faturamento do melhor mes foi R$ {total_meses[indice_melhor_mes]:,.2f} e o pior mes foi R${total_meses[indice_pior_mes]:,.2f}')

"""## 2. Continuação

Agora relacione as duas listas para printar 'O melhor mês do ano foi {} com {} vendas' e o mesmo para o pior mês do ano.



Calcule também o faturamento total do Ano e quanto que o melhor mês representou do faturamento total.

Obs: Para o faturamento total, pode usar a função sum(lista) que soma todos os itens de uma lista
"""

faturamento = sum(total_meses)
participacao_melhor_mes =  maior_venda / faturamento
print(f'O  melhor mes do ano  foi {meses[indice_melhor_mes]} e o pior mes foi {meses[indice_pior_mes]}')
print(f'O faturamento total do ano foi R$ {faturamento:,} reais')
print(f'{meses[indice_melhor_mes]} participou de {participacao_melhor_mes:.1%} do faturamento anual.')


"""## 3. Crie uma lista com o top 3 valores de vendas do ano (sem fazer "no olho")

Dica: o método remove retira um item da lista.
"""
lista_top3 = []

top1 = max(total_meses)
total_meses.remove(top1)
lista_top3.append(top1)

top2 = max(total_meses)
total_meses.remove(top2)
lista_top3.append(top2)

top3 = max(total_meses)
total_meses.remove(top3)
lista_top3.append(top3)

print(f'A venda top 1 do ano foi {lista_top3[0]:,}\nA venda top 2 do ano foi {lista_top3[1]:,}\nA venda top 3 do ano foi {lista_top3[2]:,}')
